
# DATASETS

#datasets_folder_path: 'D:/Google Drive/Disser/Code/Datasets'
datasets_folder_path: '/home/helen/Datasets'
train_data_dir: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT',
  '/ICDAR 2015/ch4_training_word_images_gt',
  '/The Street View Text/svt2/img_train',
  '/The IIIT 5K-word/train',
  # '/ICDAR OF',
]
train_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT/gt.txt',
  '/ICDAR 2015/ch4_training_word_images_gt/gt.txt',
  '/The Street View Text/svt2/train.txt',
  '/The IIIT 5K-word/train.txt',
  # '/ICDAR OF/gt.txt',
]

train_data_textzoom_dir: [
  '/TextZoom/train1',
  '/TextZoom/train2',
]

test_val_data_dir: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images',
  '/ICDAR 2015/ch4_test_word_images_gt',
  '/The Street View Text/svt2/img_test',
  '/The IIIT 5K-word/test',
  # '/ICDAR OF',
]
test_val_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images/gt.txt',
  '/ICDAR 2015/ch4_test_word_images_gt/gt.txt',
  '/The Street View Text/svt2/test.txt',
  '/The IIIT 5K-word/test.txt',
  # '/ICDAR OF/gt.txt',
]
test_val_textzoom_data_dir: [
  '/TextZoom/test/easy',
  '/TextZoom/test/medium',
  '/TextZoom/test/hard',
]

enable_lr_albumentations: False

# COMMON

width: 128
height: 64
batch_size: 192
batch_size_val: 192
epochs: 1000
lr: 0.001
scale_factor: 2
workers: 24
fp16: False

resume: '/home/helen/code/TextSR/checkpoint/log_2022-05-11_16_01_41.303808 - 69/model_best.pth'
# resume: '/home/helen/code/TextSR/checkpoint/log_2022-05-02_12_49_52.696597 - 51/checkpoint.pth'
# resume: ''

# LOSS

lambda_mse: 10
lambda_ctc: 1
clip_grad_norm_first_epochs: 200
cnt_first_epochs: 6
clip_grad_norm_: 200
adam_weight_decay: 0

# MODEL STRUCTURE

convNext_type: 'S' # T, S, L
convnext_layernorm: True
rec_best_model_save: 'lev_dis' # ssim, lev_dis, acc По какой метрике сохранять лучшую модель
# REC
acc_best_model: 'ctc' # ctc, crnn. По какому распознавателю сохранять лучшую модель
recognizer: 'lstm' # transformer или lstm.
num_lstm_layers: 2
lstm_bidirectional: True
lstm_hidden_size: 256
recognizer_input: 'att' # att, convnext. Вход распознавателя
recognizer_input_convnext: 1 # 1, 2
#SR
transpose_upsample: False
big_transpose: False

# BRANCHES

enable_sr: True
enable_ConvNext: True
enable_rec: True

freeze_sr: False
freeze_rec: False
freeze_convnext: False

train_after_sr: False

# LETTERS

letters: 'lower' # lower upper all
# большие и маленькие английские буквы + 10 цифр + 25 символов + пробел
# TGT_VOCAB_SIZE: 88
# FULL_VOCAB_SIZE: 92
# (большие или маленькие) английские буквы + 10 цифр + 25 символов + пробел
TGT_VOCAB_SIZE: 62
FULL_VOCAB_SIZE: 66
max_len: 32

# SCHEDULER

scheduler_plateau_patience: 2
scheduler_plateau_cooldown: 4
# scheduler_warmup_epoch = scheduler_plateau_cooldown
scheduler_plateau_factor: 0.8
min_lr: 1e-20

# PRETRAINED
rec_pretrained: './pretrained/ASTER.pth.tar'
moran_pretrained: './pretrained/MORAN.pth'
crnn_pretrained: './pretrained/CRNN.pth'
transformer_pretrained: './pretrained/pretrain_transformer.pth'
confuse_path: './pretrained/confuse.pkl'

# TRAIN PROCCES

displayInterval: 10 #display loss
# saveInterval: 3560000000
valInterval: -1 #-1, val at the end of epoch
AsterValInterval: 5
CrnnValInterval: 5
MoranValInterval: 5
saveBestModel: True

eval: True

cuda: True
ngpu: 1
voc_type: 'all' #'digits lower upper all'
beta1: 0.5

norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]

# manualSeed: 1234

keep_ratio: False
max_word_len: 32

vis_dir: 'demo'
