
# DATASETS

#datasets_folder_path: 'D:/Google Drive/Disser/Code/Datasets'
datasets_folder_path: '/home/helen/Datasets'
train_data_dir: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT',
  '/ICDAR 2015/ch4_training_word_images_gt',
  '/The Street View Text/svt2/img_train',
  '/The IIIT 5K-word/train',
  # '/ICDAR OF',
]
train_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT/gt.txt',
  '/ICDAR 2015/ch4_training_word_images_gt/gt.txt',
  '/The Street View Text/svt2/train.txt',
  '/The IIIT 5K-word/train.txt',
  # '/ICDAR OF/gt.txt',
]

train_data_textzoom_dir: [
  '/TextZoom/train1',
  '/TextZoom/train2',
]

test_val_data_dir: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images',
  '/ICDAR 2015/ch4_test_word_images_gt',
  '/The Street View Text/svt2/img_test',
  '/The IIIT 5K-word/test',
  # '/ICDAR OF',
]
test_val_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images/gt.txt',
  '/ICDAR 2015/ch4_test_word_images_gt/gt.txt',
  '/The Street View Text/svt2/test.txt',
  '/The IIIT 5K-word/test.txt',
  # '/ICDAR OF/gt.txt',
]
test_val_textzoom_data_dir: [
  '/TextZoom/test/easy',
  '/TextZoom/test/medium',
  '/TextZoom/test/hard',
]

# COMMON

width: 128
height: 64
batch_size: 1700
batch_size_val: 600
epochs: 1000
lr: 0.001
scale_factor: 4
workers: 24
fp16: True

# resume: '/home/helen/code/TextSR/checkpoint/log_2022-04-25_02_21_43.606800 - 39/model_best.pth'
# resume: '/home/helen/ssd/checkpoint/log_2022-04-28_03_27_08.635572/checkpoint.pth'
resume: ''

# LOSS

lambda_mse: 10
lambda_ctc: 1

# MODEL STRUCTURE

convNext_type: 'L' # T, S, L
acc_best_model: 'ctc' # ctc, crnn. По какому распознавателю сохранять лучшую модель
rec_best_model_save: 'ssim' # ssim, lev_dis, acc По какой метрике сохранять лучшую модель
recognizer: 'lstm' # transformer или lstm.
recognizer_input: 'convnext' # att, convnext. Вход распознавателя
recognizer_input_convnext: 1 # 1, 2

# BRANCHES

enable_sr: True
enable_ConvNext: True
enable_rec: False

freeze_sr: False
freeze_rec: False
freeze_convnext: False

train_after_sr: False

# LETTERS

letters: 'lower' # lower upper all
# большие и маленькие английские буквы + 10 цифр + 25 символов + пробел
# TGT_VOCAB_SIZE: 88
# FULL_VOCAB_SIZE: 92
# (большие или маленькие) английские буквы + 10 цифр + 25 символов + пробел
TGT_VOCAB_SIZE: 62
FULL_VOCAB_SIZE: 66
max_len: 32

# SCHEDULER

scheduler_plateau_patience: 5
scheduler_plateau_cooldown: 6
# scheduler_warmup_epoch = scheduler_plateau_cooldown
scheduler_plateau_factor: 0.8
min_lr: 1e-20

# PRETRAINED
rec_pretrained: './pretrained/ASTER.pth.tar'
moran_pretrained: './pretrained/MORAN.pth'
crnn_pretrained: './pretrained/CRNN.pth'
transformer_pretrained: './pretrained/pretrain_transformer.pth'
confuse_path: './pretrained/confuse.pkl'

# TRAIN PROCCES

displayInterval: 10 #display loss
# saveInterval: 3560000000
valInterval: -1 #-1, val at the end of epoch
AsterValInterval: 50
CrnnValInterval: 50
MoranValInterval: 50
saveBestModel: True

eval: True

cuda: True
ngpu: 1
voc_type: 'all' #'digits lower upper all'
beta1: 0.5

norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]

# manualSeed: 1234

keep_ratio: False
max_word_len: 32

vis_dir: 'demo'
