
# DATASETS

#datasets_folder_path: 'D:/Google Drive/Disser/Code/Datasets'
datasets_folder_path: '~/Datasets'
train_data_dir_of: [
  '/ICDAR OF',
]
train_data_annotations_file_of: [
  '/ICDAR OF/gt.txt',
]
train_data_dir: [
  # '/ICDAR 2013/Challenge2_Training_Task3_Images_GT',
  # '/ICDAR 2015/ch4_training_word_images_gt',
  # '/The Street View Text/svt2/img_train',
  # '/The IIIT 5K-word/train',
]
train_data_annotations_file: [
  # '/ICDAR 2013/Challenge2_Training_Task3_Images_GT/gt.txt',
  # '/ICDAR 2015/ch4_training_word_images_gt/gt.txt',
  # '/The Street View Text/svt2/train.txt',
  # '/The IIIT 5K-word/train.txt',
]

train_data_textzoom_dir: [
  '/TextZoom/train1',
  '/TextZoom/train2',
]

test_val_data_dir_of: [
  '/ICDAR OF',
]
test_val_data_annotations_file_of: [
  '/ICDAR OF/gt.txt',
]
test_val_data_dir: [
  # '/ICDAR 2013/Challenge2_Test_Task3_Images',
  # '/ICDAR 2015/ch4_test_word_images_gt',
  # '/The Street View Text/svt2/img_test',
  # '/The IIIT 5K-word/test',
]
test_val_data_annotations_file: [
  # '/ICDAR 2013/Challenge2_Test_Task3_Images/gt.txt',
  # '/ICDAR 2015/ch4_test_word_images_gt/gt.txt',
  # '/The Street View Text/svt2/test.txt',
  # '/The IIIT 5K-word/test.txt',
]
test_val_textzoom_data_dir: [
  '/TextZoom/test/easy',
  '/TextZoom/test/medium',
  '/TextZoom/test/hard',
]

TextZoom: 'mix' # 'mix', 'syn', 'real'

input_mask: True

overfitting: False

enable_first_albumentations: True
enable_lr_albumentations: True
enable_first_albumentations_TextZoom: True
enable_lr_albumentations_TextZoom: True

# COMMON

width: 128
height: 64
batch_size: 160
batch_size_val: 160
epochs: 1000
lr: 0.001
scale_factor: 2
workers: 24
fp16: False

# resume: '/home/helen/code/TextSR/checkpoint/log_2022-04-20_12_08_44.120870 - 28/model_best.pth'
# resume: '/home/helen/code/TextSR/checkpoint/log_2022-04-26_01_00_16.552947 - 42/model_best.pth'
# resume: '/home/helen/code/TextSR/checkpoint/log_2022-05-13_03_27_43.121425 - 73/checkpoint.pth'
# resume: '/home/helen/code/TextSR/checkpoint/log_2022-05-11_16_01_41.303808 - 69/model_best.pth'
# resume: 'checkpoint/log_2022-06-20_12_17_49.038105/checkpoint.pth'
resume: ''

# LOSS

lambda_mse: 1
lambda_ctc: 0.004
lambda_gradient: 1

clip_grad_norm_first_epochs: 200
cnt_first_epochs: 2
clip_grad_norm_: 0.5
adam_weight_decay: 0
gradient_loss: True

# MODEL STRUCTURE

stn: True

convNext_type: 'L' # T, S, L
convnext_layernorm: True
rec_best_model_save: 'ssim' # ssim, lev_dis, acc По какой метрике сохранять лучшую модель
# REC
acc_best_model: 'ctc' # ctc, crnn. По какому распознавателю сохранять лучшую модель
recognizer: 'lstm' # transformer или lstm.
num_lstm_layers: 1
lstm_bidirectional: False
lstm_hidden_size: 256
recognizer_input: 'att' # att, convnext. Вход распознавателя
recognizer_input_convnext: 1 # 1, 2
moran_att: False
#SR
transpose_upsample: False
transpose_type: 'med' # big med small

batch_norm: True

# BRANCHES

enable_sr: True
enable_ConvNext: True
enable_rec: False

freeze_sr: False
freeze_rec: False
freeze_convnext: False

train_after_sr: False

# LETTERS

letters: 'lower' # lower upper all
allow_symbols: False
# большие и маленькие английские буквы + 10 цифр + 25 символов + пробел
# TGT_VOCAB_SIZE: 88
# FULL_VOCAB_SIZE: 92
# (большие или маленькие) английские буквы + 10 цифр + 25 символов + пробел
# TGT_VOCAB_SIZE: 62
# FULL_VOCAB_SIZE: 66
# (большие или маленькие) английские буквы + 10 цифр + пробел
TGT_VOCAB_SIZE: 36
FULL_VOCAB_SIZE: 40
max_len: 32

# SCHEDULER

scheduler_plateau_patience: 2
scheduler_plateau_cooldown: 4
# scheduler_warmup_epoch = scheduler_plateau_cooldown
scheduler_plateau_factor: 0.8
min_lr: 1e-20

# PRETRAINED
rec_pretrained: './pretrained/ASTER.pth.tar'
moran_pretrained: './pretrained/MORAN.pth'
crnn_pretrained: './pretrained/CRNN.pth'
transformer_pretrained: './pretrained/pretrain_transformer.pth'
confuse_path: './pretrained/confuse.pkl'

# TRAIN PROCCES

displayInterval: 10 #display loss
# saveInterval: 3560000000
valInterval: -1 #-1, val at the end of epoch
AsterValInterval: 20
CrnnValInterval: 20
MoranValInterval: 20
saveBestModel: True

eval: True

cuda: True
ngpu: 1
voc_type: 'all' #'digits lower upper all'
beta1: 0.5

norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]

# manualSeed: 1234

keep_ratio: False
max_word_len: 32

vis_dir: 'demo'

test_time: False
test_only: False
