
# DATASETS

#datasets_folder_path: 'D:/Google Drive/Disser/Code/Datasets'
datasets_folder_path: '/home/helen/Datasets'
train_data_dir: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT',
  '/ICDAR 2015/ch4_training_word_images_gt',
  '/The Street View Text/svt2/img_train',
  '/The IIIT 5K-word/train',
  # '/ICDAR OF',
]
train_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Training_Task3_Images_GT/gt.txt',
  '/ICDAR 2015/ch4_training_word_images_gt/gt.txt',
  '/The Street View Text/svt2/train.txt',
  '/The IIIT 5K-word/train.txt',
  # '/ICDAR OF/gt.txt',
]

train_data_textzoom_dir: [
  '/TextZoom/train1',
  '/TextZoom/train2',
]

test_val_data_dir: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images',
  '/ICDAR 2015/ch4_test_word_images_gt',
  '/The Street View Text/svt2/img_test',
  '/The IIIT 5K-word/test',
  # '/ICDAR OF',
]
test_val_data_annotations_file: [
  '/ICDAR 2013/Challenge2_Test_Task3_Images/gt.txt',
  '/ICDAR 2015/ch4_test_word_images_gt/gt.txt',
  '/The Street View Text/svt2/test.txt',
  '/The IIIT 5K-word/test.txt',
  # '/ICDAR OF/gt.txt',
]
test_val_textzoom_data_dir: [
  '/TextZoom/test/easy',
  '/TextZoom/test/medium',
  '/TextZoom/test/hard',
]

# MODEL

scale_factor: 2
width: 64
height: 32
convNext_type: 'S' # T, S, L


# TRAIN PROCCES

enable_sr: True
enable_ConvNext: True
enable_rec: True

freeze_sr: False
freeze_rec: False
freeze_convnext: False

train_after_sr: False

batch_size: 70
epochs: 1000
cuda: True
ngpu: 1
workers: 24
lr: 0.001

scheduler_plateau_patience: 2
scheduler_plateau_cooldown: 6
# scheduler_warmup_epoch = scheduler_plateau_cooldown
scheduler_plateau_factor: 0.8
min_lr: 1e-20

# resume: '/home/helen/code/TextSR/checkpoint/log_2022-04-25_02_21_43.606800 - 39/model_best.pth'
# resume: '/home/helen/ssd/checkpoint/log_2022-04-25_21_53_18.130641/checkpoint.pth'
resume: ''

displayInterval: 10 #display loss
# saveInterval: 3560000000
saveBestModel: True

# manualSeed: 1234

ckpt_dir: './ckpt/'
voc_type: 'all' #'digits lower upper all'
adadelta: False
adam: True
beta1: 0.5
keep_ratio: False
max_word_len: 32

letters: 'lower' # lower upper all
# большие и маленькие английские буквы + 10 цифр + 25 символов + пробел
# TGT_VOCAB_SIZE: 88
# FULL_VOCAB_SIZE: 92
# (большие или маленькие) английские буквы + 10 цифр + 25 символов + пробел
TGT_VOCAB_SIZE: 62
FULL_VOCAB_SIZE: 66
max_len: 32

# LOSS

lambda_mse: 10
lambda_ctc: 1

acc_best_model: 'ctc' # ctc, crnn. По какому распознавателю сохранять лучшую модель
rec_best_model_save: 'lev_dis' # lev_dis, acc По какой метрике сохранять лучшую модель распознавания
recognizer: 'lstm' # transformer или lstm.
recognizer_input: 'att' # att, convnext. Вход распознавателя
recognizer_input_convnext: 1 # 1, 2

fp16: True

n_vis: 10
vis_dir: 'demo'
valInterval: -1 #-1, val at the end of epoch
rec_pretrained: './pretrained/ASTER.pth.tar'
moran_pretrained: './pretrained/MORAN.pth'
crnn_pretrained: './pretrained/CRNN.pth'
transformer_pretrained: './pretrained/pretrain_transformer.pth'
confuse_path: './pretrained/confuse.pkl'

norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]

eval: True

CONVERT:
  n_convert: 10
